name: Iosevka Paper Release Workflow

on:
    push:
        paths:
            - "private-build-plans.toml"
    workflow_dispatch: # Allows manual triggering

permissions:
    contents: read
    packages: write

jobs:
    build:
        name: Build Custom Iosevka Font
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Your Repository
              uses: actions/checkout@v4

            - name: Checkout Iosevka Repository
              uses: actions/checkout@v4
              with:
                  repository: be5invis/Iosevka
                  path: iosevka

            - name: Copy Build Plans
              run: |
                  cp private-build-plans.toml iosevka/private-build-plans.toml

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install ttfautohint
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends ttfautohint

            - name: Build Custom Font
              working-directory: iosevka
              run: |
                  npm install
                  npm run build -- contents::IosevkaPaper

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ github.run_number }}
                  release_name: Release ${{ github.run_number }}
                  draft: false
                  prerelease: false

            - name: Upload Release Assets
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./iosevka/dist/
                  asset_name: iosevka-paper-fonts.zip
                  asset_content_type: application/zip
